/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "conv_32b_8b_synth_synth_synth.v:1" *)
module conv_32b_8b_synth_synth_synth(clk_4f, clk_f, data_in, valid_in, valid_out, data_out);
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  wire [2:0] _000_;
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  wire [7:0] _001_;
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  wire [2:0] _002_;
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  wire [2:0] _003_;
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  wire [2:0] _004_;
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  wire [2:0] _005_;
  (* src = "conv_32b_8b_synth_synth_synth.v:23" *)
  (* unused_bits = "3" *)
  wire [31:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire [2:0] _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire [7:0] _016_;
  wire [7:0] _017_;
  wire [7:0] _018_;
  wire [7:0] _019_;
  (* src = "conv_32b_8b_synth_synth_synth.v:33|paralelo_serial_synth_synth.v:54|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _020_;
  (* src = "conv_32b_8b_synth_synth_synth.v:1" *)
  input clk_4f;
  (* src = "conv_32b_8b_synth_synth_synth.v:2" *)
  input clk_f;
  (* src = "conv_32b_8b_synth_synth_synth.v:8" *)
  reg [2:0] contador;
  (* src = "conv_32b_8b_synth_synth_synth.v:3" *)
  input [31:0] data_in;
  (* src = "conv_32b_8b_synth_synth_synth.v:6" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "conv_32b_8b_synth_synth_synth.v:4" *)
  input valid_in;
  (* src = "conv_32b_8b_synth_synth_synth.v:5" *)
  output valid_out;
  reg valid_out;
  assign _007_ = _006_[0] |(* src = "conv_32b_8b_synth_synth_synth.v:26" *)  contador[1];
  assign _013_ = _007_ |(* src = "conv_32b_8b_synth_synth_synth.v:26" *)  contador[2];
  assign _008_ = contador[0] |(* src = "conv_32b_8b_synth_synth_synth.v:31" *)  _012_[1];
  assign _014_ = _008_ |(* src = "conv_32b_8b_synth_synth_synth.v:31" *)  contador[2];
  assign _009_ = _006_[0] |(* src = "conv_32b_8b_synth_synth_synth.v:36" *)  _012_[1];
  assign _015_ = _009_ |(* src = "conv_32b_8b_synth_synth_synth.v:36" *)  contador[2];
  assign _010_ = contador[0] |(* src = "conv_32b_8b_synth_synth_synth.v:21" *)  contador[1];
  assign _011_ = _010_ |(* src = "conv_32b_8b_synth_synth_synth.v:21" *)  contador[2];
  assign _005_[0] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) contador[0] : 1'h0;
  assign _005_[1] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) contador[1] : 1'h0;
  assign _005_[2] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) contador[2] : 1'h0;
  assign _004_[0] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _005_[0] : _006_[0];
  assign _004_[1] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _005_[1] : _006_[1];
  assign _004_[2] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _005_[2] : _006_[2];
  assign _003_[0] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _004_[0] : _006_[0];
  assign _003_[1] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _004_[1] : _006_[1];
  assign _003_[2] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _004_[2] : _006_[2];
  assign _000_[0] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _002_[0] : 1'h0;
  assign _000_[1] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _002_[1] : 1'h0;
  assign _000_[2] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _002_[2] : 1'h0;
  assign _002_[0] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _003_[0] : _006_[0];
  assign _002_[1] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _003_[1] : _006_[1];
  assign _002_[2] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _003_[2] : _006_[2];
  assign _016_[0] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[0] : data_in[16];
  assign _016_[1] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[1] : data_in[17];
  assign _016_[2] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[2] : data_in[18];
  assign _016_[3] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[3] : data_in[19];
  assign _016_[4] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[4] : data_in[20];
  assign _016_[5] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[5] : data_in[21];
  assign _016_[6] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[6] : data_in[22];
  assign _016_[7] = _013_ ? (* src = "conv_32b_8b_synth_synth_synth.v:26" *) _019_[7] : data_in[23];
  assign _018_[0] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[0] : data_in[0];
  assign _018_[1] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[1] : data_in[1];
  assign _018_[2] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[2] : data_in[2];
  assign _018_[3] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[3] : data_in[3];
  assign _018_[4] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[4] : data_in[4];
  assign _018_[5] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[5] : data_in[5];
  assign _018_[6] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[6] : data_in[6];
  assign _018_[7] = _015_ ? (* src = "conv_32b_8b_synth_synth_synth.v:36" *) data_out[7] : data_in[7];
  assign _019_[0] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[0] : data_in[8];
  assign _019_[1] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[1] : data_in[9];
  assign _019_[2] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[2] : data_in[10];
  assign _019_[3] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[3] : data_in[11];
  assign _019_[4] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[4] : data_in[12];
  assign _019_[5] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[5] : data_in[13];
  assign _019_[6] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[6] : data_in[14];
  assign _019_[7] = _014_ ? (* src = "conv_32b_8b_synth_synth_synth.v:31" *) _018_[7] : data_in[15];
  assign _017_[0] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[0] : data_in[24];
  assign _017_[1] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[1] : data_in[25];
  assign _017_[2] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[2] : data_in[26];
  assign _017_[3] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[3] : data_in[27];
  assign _017_[4] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[4] : data_in[28];
  assign _017_[5] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[5] : data_in[29];
  assign _017_[6] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[6] : data_in[30];
  assign _017_[7] = _011_ ? (* src = "conv_32b_8b_synth_synth_synth.v:21" *) _016_[7] : data_in[31];
  assign _001_[0] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[0] : 1'hx;
  assign _001_[1] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[1] : 1'hx;
  assign _001_[2] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[2] : 1'hx;
  assign _001_[3] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[3] : 1'hx;
  assign _001_[4] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[4] : 1'hx;
  assign _001_[5] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[5] : 1'hx;
  assign _001_[6] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[6] : 1'hx;
  assign _001_[7] = valid_in ? (* src = "conv_32b_8b_synth_synth_synth.v:19" *) _017_[7] : 1'hx;
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[0] <= _001_[0];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[1] <= _001_[1];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[2] <= _001_[2];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[3] <= _001_[3];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[4] <= _001_[4];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[5] <= _001_[5];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[6] <= _001_[6];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      data_out[7] <= _001_[7];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      valid_out <= valid_in;
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      contador[0] <= _000_[0];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      contador[1] <= _000_[1];
  (* src = "conv_32b_8b_synth_synth_synth.v:17" *)
  always @(posedge clk_4f)
      contador[2] <= _000_[2];
  assign _006_[0] = contador[0] ^(* src = "conv_32b_8b_synth_synth_synth.v:36" *)  1'h1;
  assign _012_[1] = contador[1] ^(* src = "conv_32b_8b_synth_synth_synth.v:36" *)  1'h1;
  assign _006_[1] = contador[1] ^(* src = "conv_32b_8b_synth_synth_synth.v:33|paralelo_serial_synth_synth.v:54|<techmap.v>:263" *)  contador[0];
  assign _006_[2] = contador[2] ^(* src = "conv_32b_8b_synth_synth_synth.v:33|paralelo_serial_synth_synth.v:54|<techmap.v>:263" *)  _020_[1];
  assign _020_[1] = contador[1] &(* src = "conv_32b_8b_synth_synth_synth.v:33|paralelo_serial_synth_synth.v:54|<techmap.v>:260|<techmap.v>:221" *)  contador[0];
  assign _006_[31:4] = 28'h0000000;
  assign { _012_[2], _012_[0] } = { contador[2], contador[0] };
  assign { _020_[31:2], _020_[0] } = { 29'h00000000, _006_[3], contador[0] };
endmodule

(* src = "paralelo_serial_synth_synth.v:1" *)
module paralelo_serial_synth_synth(clk_4f, clk_32f, data_in, valid_in, reset, data2send, data_out);
  (* src = "paralelo_serial_synth_synth.v:32" *)
  wire [7:0] _000_;
  (* src = "paralelo_serial_synth_synth.v:32" *)
  wire _001_;
  (* src = "paralelo_serial_synth_synth.v:32" *)
  wire [2:0] _002_;
  (* src = "paralelo_serial_synth_synth.v:32" *)
  wire [2:0] _003_;
  (* src = "paralelo_serial_synth_synth.v:54" *)
  (* unused_bits = "3" *)
  wire [31:0] _004_;
  (* src = "paralelo_serial_synth_synth.v:74" *)
  (* unused_bits = "3" *)
  wire [31:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire [1:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire [3:0] _019_;
  wire [1:0] _020_;
  wire [3:0] _021_;
  wire [1:0] _022_;
  wire _023_;
  wire _024_;
  wire [2:0] _025_;
  wire [2:0] _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire [2:0] _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  (* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:432" *)
  wire [7:0] _051_;
  (* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:428" *)
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire [7:0] _063_;
  wire [2:0] _064_;
  (* src = "paralelo_serial_synth_synth.v:54|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _065_;
  (* src = "paralelo_serial_synth_synth.v:74|paralelo_serial_synth_synth.v:54|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _066_;
  (* src = "paralelo_serial_synth_synth.v:68|paralelo_serial_synth_synth.v:60|<techmap.v>:445" *)
  wire _067_;
  (* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)
  wire _068_;
  (* src = "paralelo_serial_synth_synth.v:3" *)
  input clk_32f;
  (* src = "paralelo_serial_synth_synth.v:2" *)
  input clk_4f;
  (* src = "paralelo_serial_synth_synth.v:7" *)
  output [7:0] data2send;
  reg [7:0] data2send;
  (* src = "paralelo_serial_synth_synth.v:4" *)
  input [7:0] data_in;
  (* src = "paralelo_serial_synth_synth.v:8" *)
  output data_out;
  reg data_out;
  (* src = "paralelo_serial_synth_synth.v:6" *)
  input reset;
  (* src = "paralelo_serial_synth_synth.v:10" *)
  reg [2:0] selector1;
  (* src = "paralelo_serial_synth_synth.v:11" *)
  reg [2:0] selector2;
  (* src = "paralelo_serial_synth_synth.v:5" *)
  input valid_in;
  assign _008_ = _049_ | _044_;
  assign _006_ = _008_ | _043_;
  assign _009_[0] = _050_ | _048_;
  assign _009_[1] = _047_ | _046_;
  assign _010_ = _009_[0] | _009_[1];
  assign _007_ = _010_ | _045_;
  assign _027_ = _011_ |(* src = "paralelo_serial_synth_synth.v:68|paralelo_serial_synth_synth.v:60" *)  _025_[2];
  assign _028_ = _012_ |(* src = "paralelo_serial_synth_synth.v:67|paralelo_serial_synth_synth.v:60" *)  _025_[2];
  assign _029_ = _013_ |(* src = "paralelo_serial_synth_synth.v:66|paralelo_serial_synth_synth.v:60" *)  _025_[2];
  assign _030_ = _014_ |(* src = "paralelo_serial_synth_synth.v:65|paralelo_serial_synth_synth.v:60" *)  _025_[2];
  assign _011_ = _005_[0] |(* src = "paralelo_serial_synth_synth.v:64|paralelo_serial_synth_synth.v:60" *)  _025_[1];
  assign _031_ = _011_ |(* src = "paralelo_serial_synth_synth.v:64|paralelo_serial_synth_synth.v:60" *)  selector2[2];
  assign _012_ = selector2[0] |(* src = "paralelo_serial_synth_synth.v:63|paralelo_serial_synth_synth.v:60" *)  _025_[1];
  assign _032_ = _012_ |(* src = "paralelo_serial_synth_synth.v:63|paralelo_serial_synth_synth.v:60" *)  selector2[2];
  assign _013_ = _005_[0] |(* src = "paralelo_serial_synth_synth.v:62|paralelo_serial_synth_synth.v:60" *)  selector2[1];
  assign _033_ = _013_ |(* src = "paralelo_serial_synth_synth.v:62|paralelo_serial_synth_synth.v:60" *)  selector2[2];
  assign _034_ = _015_ |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40" *)  _026_[2];
  assign _035_ = _016_ |(* src = "paralelo_serial_synth_synth.v:47|paralelo_serial_synth_synth.v:40" *)  _026_[2];
  assign _036_ = _017_ |(* src = "paralelo_serial_synth_synth.v:46|paralelo_serial_synth_synth.v:40" *)  _026_[2];
  assign _037_ = _018_ |(* src = "paralelo_serial_synth_synth.v:45|paralelo_serial_synth_synth.v:40" *)  _026_[2];
  assign _015_ = _004_[0] |(* src = "paralelo_serial_synth_synth.v:44|paralelo_serial_synth_synth.v:40" *)  _026_[1];
  assign _038_ = _015_ |(* src = "paralelo_serial_synth_synth.v:44|paralelo_serial_synth_synth.v:40" *)  selector1[2];
  assign _016_ = selector1[0] |(* src = "paralelo_serial_synth_synth.v:43|paralelo_serial_synth_synth.v:40" *)  _026_[1];
  assign _039_ = _016_ |(* src = "paralelo_serial_synth_synth.v:43|paralelo_serial_synth_synth.v:40" *)  selector1[2];
  assign _017_ = _004_[0] |(* src = "paralelo_serial_synth_synth.v:42|paralelo_serial_synth_synth.v:40" *)  selector1[1];
  assign _040_ = _017_ |(* src = "paralelo_serial_synth_synth.v:42|paralelo_serial_synth_synth.v:40" *)  selector1[2];
  assign _067_ = _006_ |(* src = "paralelo_serial_synth_synth.v:68|paralelo_serial_synth_synth.v:60|<techmap.v>:445" *)  _007_;
  assign _019_[0] = _051_[0] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:441" *)  _051_[1];
  assign _019_[1] = _051_[2] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:441" *)  _051_[3];
  assign _019_[2] = _051_[4] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:441" *)  _051_[5];
  assign _019_[3] = _051_[6] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:441" *)  _051_[7];
  assign _020_[0] = _019_[0] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:441" *)  _019_[1];
  assign _020_[1] = _019_[2] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:441" *)  _019_[3];
  assign _052_ = _020_[0] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:441" *)  _020_[1];
  assign _021_[0] = _054_ |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)  _055_;
  assign _021_[1] = _056_ |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)  _057_;
  assign _021_[2] = _058_ |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)  _059_;
  assign _021_[3] = _060_ |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)  _061_;
  assign _022_[0] = _021_[0] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)  _021_[1];
  assign _022_[1] = _021_[2] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)  _021_[3];
  assign _068_ = _022_[0] |(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *)  _022_[1];
  assign _014_ = selector2[0] |(* src = "paralelo_serial_synth_synth.v:61|paralelo_serial_synth_synth.v:60" *)  selector2[1];
  assign _023_ = _014_ |(* src = "paralelo_serial_synth_synth.v:61|paralelo_serial_synth_synth.v:60" *)  selector2[2];
  assign _018_ = selector1[0] |(* src = "paralelo_serial_synth_synth.v:41|paralelo_serial_synth_synth.v:40" *)  selector1[1];
  assign _024_ = _018_ |(* src = "paralelo_serial_synth_synth.v:41|paralelo_serial_synth_synth.v:40" *)  selector1[2];
  assign _043_ = ~(* src = "paralelo_serial_synth_synth.v:68|paralelo_serial_synth_synth.v:60" *) _027_;
  assign _044_ = ~(* src = "paralelo_serial_synth_synth.v:67|paralelo_serial_synth_synth.v:60" *) _028_;
  assign _045_ = ~(* src = "paralelo_serial_synth_synth.v:66|paralelo_serial_synth_synth.v:60" *) _029_;
  assign _046_ = ~(* src = "paralelo_serial_synth_synth.v:65|paralelo_serial_synth_synth.v:60" *) _030_;
  assign _047_ = ~(* src = "paralelo_serial_synth_synth.v:64|paralelo_serial_synth_synth.v:60" *) _031_;
  assign _048_ = ~(* src = "paralelo_serial_synth_synth.v:63|paralelo_serial_synth_synth.v:60" *) _032_;
  assign _049_ = ~(* src = "paralelo_serial_synth_synth.v:62|paralelo_serial_synth_synth.v:60" *) _033_;
  assign _050_ = ~(* src = "paralelo_serial_synth_synth.v:61|paralelo_serial_synth_synth.v:60" *) _023_;
  assign _054_ = ~(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40" *) _034_;
  assign _055_ = ~(* src = "paralelo_serial_synth_synth.v:47|paralelo_serial_synth_synth.v:40" *) _035_;
  assign _056_ = ~(* src = "paralelo_serial_synth_synth.v:46|paralelo_serial_synth_synth.v:40" *) _036_;
  assign _057_ = ~(* src = "paralelo_serial_synth_synth.v:45|paralelo_serial_synth_synth.v:40" *) _037_;
  assign _058_ = ~(* src = "paralelo_serial_synth_synth.v:44|paralelo_serial_synth_synth.v:40" *) _038_;
  assign _059_ = ~(* src = "paralelo_serial_synth_synth.v:43|paralelo_serial_synth_synth.v:40" *) _039_;
  assign _060_ = ~(* src = "paralelo_serial_synth_synth.v:42|paralelo_serial_synth_synth.v:40" *) _040_;
  assign _061_ = ~(* src = "paralelo_serial_synth_synth.v:41|paralelo_serial_synth_synth.v:40" *) _024_;
  assign _041_[0] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) _004_[0] : selector1[0];
  assign _041_[1] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) _004_[1] : selector1[1];
  assign _041_[2] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) _004_[2] : selector1[2];
  assign _002_[0] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _041_[0];
  assign _002_[1] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _041_[1];
  assign _002_[2] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _041_[2];
  assign _062_ = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) _053_ : _042_;
  assign _001_ = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _062_;
  assign _064_[0] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) selector2[0] : _005_[0];
  assign _064_[1] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) selector2[1] : _005_[1];
  assign _064_[2] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) selector2[2] : _005_[2];
  assign _063_[0] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[0] : 1'h0;
  assign _063_[1] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[1] : 1'h0;
  assign _063_[2] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[2] : 1'h1;
  assign _063_[3] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[3] : 1'h1;
  assign _063_[4] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[4] : 1'h1;
  assign _063_[5] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[5] : 1'h1;
  assign _063_[6] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[6] : 1'h0;
  assign _063_[7] = valid_in ? (* src = "paralelo_serial_synth_synth.v:36" *) data_in[7] : 1'h1;
  assign _000_[0] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[0];
  assign _000_[1] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[1];
  assign _000_[2] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[2];
  assign _000_[3] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[3];
  assign _000_[4] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[4];
  assign _000_[5] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[5];
  assign _000_[6] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[6];
  assign _000_[7] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _063_[7];
  assign _003_[0] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _064_[0];
  assign _003_[1] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _064_[1];
  assign _003_[2] = reset ? (* src = "paralelo_serial_synth_synth.v:34" *) 1'h0 : _064_[2];
  assign _042_ = _067_ ? (* src = "paralelo_serial_synth_synth.v:68|paralelo_serial_synth_synth.v:60|<techmap.v>:445" *) _007_ : 1'hx;
  assign _053_ = _068_ ? (* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:445" *) _052_ : 1'hx;
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      selector1[0] <= _002_[0];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      selector1[1] <= _002_[1];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      selector1[2] <= _002_[2];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[0] <= _000_[0];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[1] <= _000_[1];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[2] <= _000_[2];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[3] <= _000_[3];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[4] <= _000_[4];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[5] <= _000_[5];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[6] <= _000_[6];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data2send[7] <= _000_[7];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      selector2[0] <= _003_[0];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      selector2[1] <= _003_[1];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      selector2[2] <= _003_[2];
  (* src = "paralelo_serial_synth_synth.v:32" *)
  always @(posedge clk_32f)
      data_out <= _001_;
  assign _005_[1] = selector2[1] ^(* src = "paralelo_serial_synth_synth.v:74|paralelo_serial_synth_synth.v:54|<techmap.v>:263" *)  selector2[0];
  assign _005_[2] = selector2[2] ^(* src = "paralelo_serial_synth_synth.v:74|paralelo_serial_synth_synth.v:54|<techmap.v>:263" *)  _066_[1];
  assign _065_[1] = selector1[1] &(* src = "paralelo_serial_synth_synth.v:54|<techmap.v>:260|<techmap.v>:221" *)  selector1[0];
  assign _066_[1] = selector2[1] &(* src = "paralelo_serial_synth_synth.v:74|paralelo_serial_synth_synth.v:54|<techmap.v>:260|<techmap.v>:221" *)  selector2[0];
  assign _025_[2] = selector2[2] ^(* src = "paralelo_serial_synth_synth.v:65|paralelo_serial_synth_synth.v:60" *)  1'h1;
  assign _025_[1] = selector2[1] ^(* src = "paralelo_serial_synth_synth.v:63|paralelo_serial_synth_synth.v:60" *)  1'h1;
  assign _005_[0] = selector2[0] ^(* src = "paralelo_serial_synth_synth.v:62|paralelo_serial_synth_synth.v:60" *)  1'h1;
  assign _026_[2] = selector1[2] ^(* src = "paralelo_serial_synth_synth.v:45|paralelo_serial_synth_synth.v:40" *)  1'h1;
  assign _026_[1] = selector1[1] ^(* src = "paralelo_serial_synth_synth.v:43|paralelo_serial_synth_synth.v:40" *)  1'h1;
  assign _004_[0] = selector1[0] ^(* src = "paralelo_serial_synth_synth.v:42|paralelo_serial_synth_synth.v:40" *)  1'h1;
  assign _051_[4] = data_in[4] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _058_;
  assign _051_[7] = data_in[7] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _061_;
  assign _051_[6] = data_in[6] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _060_;
  assign _051_[5] = data_in[5] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _059_;
  assign _051_[3] = data_in[3] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _057_;
  assign _051_[2] = data_in[2] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _056_;
  assign _051_[1] = data_in[1] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _055_;
  assign _051_[0] = data_in[0] &(* src = "paralelo_serial_synth_synth.v:48|paralelo_serial_synth_synth.v:40|<techmap.v>:434" *)  _054_;
  assign _004_[1] = selector1[1] ^(* src = "paralelo_serial_synth_synth.v:54|<techmap.v>:263" *)  selector1[0];
  assign _004_[2] = selector1[2] ^(* src = "paralelo_serial_synth_synth.v:54|<techmap.v>:263" *)  _065_[1];
  assign _004_[31:4] = 28'h0000000;
  assign _005_[31:4] = 28'h0000000;
  assign _025_[0] = _005_[0];
  assign _026_[0] = _004_[0];
  assign { _065_[31:2], _065_[0] } = { 29'h00000000, _004_[3], selector1[0] };
  assign { _066_[31:2], _066_[0] } = { 29'h00000000, _005_[3], selector2[0] };
endmodule

(* top =  1  *)
(* src = "phy_tx_synth.v:6" *)
module phy_tx_synth(input_bus, valid, reset, clk, clk2, clk4, clk32, serial_o0, serial_o1);
  (* src = "phy_tx_synth.v:10" *)
  input clk;
  (* src = "phy_tx_synth.v:11" *)
  input clk2;
  (* src = "phy_tx_synth.v:13" *)
  input clk32;
  (* src = "phy_tx_synth.v:12" *)
  input clk4;
  (* src = "phy_tx_synth.v:18" *)
  wire [7:0] data_out0;
  (* src = "phy_tx_synth.v:18" *)
  wire [7:0] data_out1;
  (* src = "phy_tx_synth.v:7" *)
  input [31:0] input_bus;
  (* src = "phy_tx_synth.v:17" *)
  wire [31:0] lane_0;
  (* src = "phy_tx_synth.v:17" *)
  wire [31:0] lane_1;
  (* src = "phy_tx_synth.v:9" *)
  input reset;
  (* src = "phy_tx_synth.v:14" *)
  output serial_o0;
  (* src = "phy_tx_synth.v:15" *)
  output serial_o1;
  (* src = "phy_tx_synth.v:8" *)
  input valid;
  (* src = "phy_tx_synth.v:33" *)
  (* unused_bits = "0" *)
  wire valid_out;
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_synth.v:31" *)
  conv_32b_8b_synth_synth_synth conv_32b_8b_synth_synth_synthINST0 (
    .clk_4f(clk4),
    .clk_f(clk),
    .data_in(lane_0),
    .data_out(data_out0),
    .valid_in(valid),
    .valid_out(valid_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_synth.v:41" *)
  conv_32b_8b_synth_synth_synth conv_32b_8b_synth_synth_synthINST1 (
    .clk_4f(clk4),
    .clk_f(clk),
    .data_in(lane_1),
    .data_out(data_out1),
    .valid_in(valid),
    .valid_out(valid_out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_synth.v:52" *)
  paralelo_serial_synth_synth paralelo_serial_synth_synthINST0 (
    .clk_32f(clk32),
    .clk_4f(clk4),
    .data_in(data_out0),
    .data_out(serial_o0),
    .reset(reset),
    .valid_in(valid)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_synth.v:62" *)
  paralelo_serial_synth_synth paralelo_serial_synth_synthINST1 (
    .clk_32f(clk32),
    .clk_4f(clk4),
    .data_in(data_out1),
    .data_out(serial_o1),
    .reset(reset),
    .valid_in(valid)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phy_tx_synth.v:20" *)
  striping_synth_synth striping_synth_synthINST (
    .clk_2f(clk2),
    .data_in(input_bus),
    .lane_0(lane_0),
    .lane_1(lane_1),
    .reset(reset),
    .valid_in(valid)
  );
endmodule

(* src = "striping_synth_synth.v:1" *)
module striping_synth_synth(clk_2f, data_in, valid_in, reset, lane_0, lane_1, valid_0, valid_1);
  (* src = "striping_synth_synth.v:13" *)
  wire [31:0] _000_;
  (* src = "striping_synth_synth.v:13" *)
  wire [31:0] _001_;
  (* src = "striping_synth_synth.v:13" *)
  wire _002_;
  (* src = "striping_synth_synth.v:13" *)
  wire _003_;
  (* src = "striping_synth_synth.v:13" *)
  wire _004_;
  (* src = "striping_synth_synth.v:26" *)
  wire _005_;
  (* src = "striping_synth_synth.v:39" *)
  wire _006_;
  (* src = "striping_synth_synth.v:26" *)
  wire _007_;
  (* src = "striping_synth_synth.v:33" *)
  wire _008_;
  (* src = "striping_synth_synth.v:39" *)
  wire _009_;
  (* src = "striping_synth_synth.v:44" *)
  wire _010_;
  wire [31:0] _011_;
  wire [31:0] _012_;
  wire [31:0] _013_;
  wire [31:0] _014_;
  wire [31:0] _015_;
  wire [31:0] _016_;
  wire [31:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  (* src = "striping_synth_synth.v:3" *)
  input clk_2f;
  (* src = "striping_synth_synth.v:4" *)
  input [31:0] data_in;
  (* src = "striping_synth_synth.v:7" *)
  output [31:0] lane_0;
  reg [31:0] lane_0;
  (* src = "striping_synth_synth.v:8" *)
  output [31:0] lane_1;
  reg [31:0] lane_1;
  (* src = "striping_synth_synth.v:6" *)
  input reset;
  (* src = "striping_synth_synth.v:12" *)
  reg selector;
  (* src = "striping_synth_synth.v:9" *)
  output valid_0;
  reg valid_0;
  (* src = "striping_synth_synth.v:10" *)
  output valid_1;
  reg valid_1;
  (* src = "striping_synth_synth.v:5" *)
  input valid_in;
  assign _007_ = valid_in &(* src = "striping_synth_synth.v:26" *)  _005_;
  assign _008_ = valid_in &(* src = "striping_synth_synth.v:33" *)  selector;
  assign _009_ = _006_ &(* src = "striping_synth_synth.v:39" *)  _005_;
  assign _010_ = _006_ &(* src = "striping_synth_synth.v:44" *)  selector;
  assign _013_[0] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[0] : _012_[0];
  assign _013_[1] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[1] : _012_[1];
  assign _013_[2] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[2] : _012_[2];
  assign _013_[3] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[3] : _012_[3];
  assign _013_[4] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[4] : _012_[4];
  assign _013_[5] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[5] : _012_[5];
  assign _013_[6] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[6] : _012_[6];
  assign _013_[7] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[7] : _012_[7];
  assign _013_[8] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[8] : _012_[8];
  assign _013_[9] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[9] : _012_[9];
  assign _013_[10] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[10] : _012_[10];
  assign _013_[11] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[11] : _012_[11];
  assign _013_[12] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[12] : _012_[12];
  assign _013_[13] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[13] : _012_[13];
  assign _013_[14] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[14] : _012_[14];
  assign _013_[15] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[15] : _012_[15];
  assign _013_[16] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[16] : _012_[16];
  assign _013_[17] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[17] : _012_[17];
  assign _013_[18] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[18] : _012_[18];
  assign _013_[19] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[19] : _012_[19];
  assign _013_[20] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[20] : _012_[20];
  assign _013_[21] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[21] : _012_[21];
  assign _013_[22] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[22] : _012_[22];
  assign _013_[23] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[23] : _012_[23];
  assign _013_[24] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[24] : _012_[24];
  assign _013_[25] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[25] : _012_[25];
  assign _013_[26] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[26] : _012_[26];
  assign _013_[27] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[27] : _012_[27];
  assign _013_[28] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[28] : _012_[28];
  assign _013_[29] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[29] : _012_[29];
  assign _013_[30] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[30] : _012_[30];
  assign _013_[31] = _008_ ? (* src = "striping_synth_synth.v:33" *) data_in[31] : _012_[31];
  assign _011_[0] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[0];
  assign _011_[1] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[1];
  assign _011_[2] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[2];
  assign _011_[3] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[3];
  assign _011_[4] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[4];
  assign _011_[5] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[5];
  assign _011_[6] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[6];
  assign _011_[7] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[7];
  assign _011_[8] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[8];
  assign _011_[9] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[9];
  assign _011_[10] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[10];
  assign _011_[11] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[11];
  assign _011_[12] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[12];
  assign _011_[13] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[13];
  assign _011_[14] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[14];
  assign _011_[15] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[15];
  assign _011_[16] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[16];
  assign _011_[17] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[17];
  assign _011_[18] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[18];
  assign _011_[19] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[19];
  assign _011_[20] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[20];
  assign _011_[21] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[21];
  assign _011_[22] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[22];
  assign _011_[23] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[23];
  assign _011_[24] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[24];
  assign _011_[25] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[25];
  assign _011_[26] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[26];
  assign _011_[27] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[27];
  assign _011_[28] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[28];
  assign _011_[29] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[29];
  assign _011_[30] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[30];
  assign _011_[31] = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : lane_1[31];
  assign _012_[0] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[0] : _011_[0];
  assign _012_[1] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[1] : _011_[1];
  assign _012_[2] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[2] : _011_[2];
  assign _012_[3] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[3] : _011_[3];
  assign _012_[4] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[4] : _011_[4];
  assign _012_[5] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[5] : _011_[5];
  assign _012_[6] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[6] : _011_[6];
  assign _012_[7] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[7] : _011_[7];
  assign _012_[8] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[8] : _011_[8];
  assign _012_[9] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[9] : _011_[9];
  assign _012_[10] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[10] : _011_[10];
  assign _012_[11] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[11] : _011_[11];
  assign _012_[12] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[12] : _011_[12];
  assign _012_[13] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[13] : _011_[13];
  assign _012_[14] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[14] : _011_[14];
  assign _012_[15] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[15] : _011_[15];
  assign _012_[16] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[16] : _011_[16];
  assign _012_[17] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[17] : _011_[17];
  assign _012_[18] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[18] : _011_[18];
  assign _012_[19] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[19] : _011_[19];
  assign _012_[20] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[20] : _011_[20];
  assign _012_[21] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[21] : _011_[21];
  assign _012_[22] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[22] : _011_[22];
  assign _012_[23] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[23] : _011_[23];
  assign _012_[24] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[24] : _011_[24];
  assign _012_[25] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[25] : _011_[25];
  assign _012_[26] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[26] : _011_[26];
  assign _012_[27] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[27] : _011_[27];
  assign _012_[28] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[28] : _011_[28];
  assign _012_[29] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[29] : _011_[29];
  assign _012_[30] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[30] : _011_[30];
  assign _012_[31] = _009_ ? (* src = "striping_synth_synth.v:39" *) lane_1[31] : _011_[31];
  assign _014_[0] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[0] : _013_[0];
  assign _014_[1] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[1] : _013_[1];
  assign _014_[2] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[2] : _013_[2];
  assign _014_[3] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[3] : _013_[3];
  assign _014_[4] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[4] : _013_[4];
  assign _014_[5] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[5] : _013_[5];
  assign _014_[6] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[6] : _013_[6];
  assign _014_[7] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[7] : _013_[7];
  assign _014_[8] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[8] : _013_[8];
  assign _014_[9] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[9] : _013_[9];
  assign _014_[10] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[10] : _013_[10];
  assign _014_[11] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[11] : _013_[11];
  assign _014_[12] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[12] : _013_[12];
  assign _014_[13] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[13] : _013_[13];
  assign _014_[14] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[14] : _013_[14];
  assign _014_[15] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[15] : _013_[15];
  assign _014_[16] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[16] : _013_[16];
  assign _014_[17] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[17] : _013_[17];
  assign _014_[18] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[18] : _013_[18];
  assign _014_[19] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[19] : _013_[19];
  assign _014_[20] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[20] : _013_[20];
  assign _014_[21] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[21] : _013_[21];
  assign _014_[22] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[22] : _013_[22];
  assign _014_[23] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[23] : _013_[23];
  assign _014_[24] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[24] : _013_[24];
  assign _014_[25] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[25] : _013_[25];
  assign _014_[26] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[26] : _013_[26];
  assign _014_[27] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[27] : _013_[27];
  assign _014_[28] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[28] : _013_[28];
  assign _014_[29] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[29] : _013_[29];
  assign _014_[30] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[30] : _013_[30];
  assign _014_[31] = _007_ ? (* src = "striping_synth_synth.v:26" *) lane_1[31] : _013_[31];
  assign _001_[0] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[0];
  assign _001_[1] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[1];
  assign _001_[2] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[2];
  assign _001_[3] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[3];
  assign _001_[4] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[4];
  assign _001_[5] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[5];
  assign _001_[6] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[6];
  assign _001_[7] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[7];
  assign _001_[8] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[8];
  assign _001_[9] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[9];
  assign _001_[10] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[10];
  assign _001_[11] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[11];
  assign _001_[12] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[12];
  assign _001_[13] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[13];
  assign _001_[14] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[14];
  assign _001_[15] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[15];
  assign _001_[16] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[16];
  assign _001_[17] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[17];
  assign _001_[18] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[18];
  assign _001_[19] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[19];
  assign _001_[20] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[20];
  assign _001_[21] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[21];
  assign _001_[22] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[22];
  assign _001_[23] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[23];
  assign _001_[24] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[24];
  assign _001_[25] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[25];
  assign _001_[26] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[26];
  assign _001_[27] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[27];
  assign _001_[28] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[28];
  assign _001_[29] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[29];
  assign _001_[30] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[30];
  assign _001_[31] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _014_[31];
  assign _017_[0] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[0] : _016_[0];
  assign _017_[1] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[1] : _016_[1];
  assign _017_[2] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[2] : _016_[2];
  assign _017_[3] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[3] : _016_[3];
  assign _017_[4] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[4] : _016_[4];
  assign _017_[5] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[5] : _016_[5];
  assign _017_[6] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[6] : _016_[6];
  assign _017_[7] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[7] : _016_[7];
  assign _017_[8] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[8] : _016_[8];
  assign _017_[9] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[9] : _016_[9];
  assign _017_[10] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[10] : _016_[10];
  assign _017_[11] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[11] : _016_[11];
  assign _017_[12] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[12] : _016_[12];
  assign _017_[13] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[13] : _016_[13];
  assign _017_[14] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[14] : _016_[14];
  assign _017_[15] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[15] : _016_[15];
  assign _017_[16] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[16] : _016_[16];
  assign _017_[17] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[17] : _016_[17];
  assign _017_[18] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[18] : _016_[18];
  assign _017_[19] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[19] : _016_[19];
  assign _017_[20] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[20] : _016_[20];
  assign _017_[21] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[21] : _016_[21];
  assign _017_[22] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[22] : _016_[22];
  assign _017_[23] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[23] : _016_[23];
  assign _017_[24] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[24] : _016_[24];
  assign _017_[25] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[25] : _016_[25];
  assign _017_[26] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[26] : _016_[26];
  assign _017_[27] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[27] : _016_[27];
  assign _017_[28] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[28] : _016_[28];
  assign _017_[29] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[29] : _016_[29];
  assign _017_[30] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[30] : _016_[30];
  assign _017_[31] = _007_ ? (* src = "striping_synth_synth.v:26" *) data_in[31] : _016_[31];
  assign _015_[0] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[0];
  assign _015_[1] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[1];
  assign _015_[2] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[2];
  assign _015_[3] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[3];
  assign _015_[4] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[4];
  assign _015_[5] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[5];
  assign _015_[6] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[6];
  assign _015_[7] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[7];
  assign _015_[8] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[8];
  assign _015_[9] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[9];
  assign _015_[10] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[10];
  assign _015_[11] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[11];
  assign _015_[12] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[12];
  assign _015_[13] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[13];
  assign _015_[14] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[14];
  assign _015_[15] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[15];
  assign _015_[16] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[16];
  assign _015_[17] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[17];
  assign _015_[18] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[18];
  assign _015_[19] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[19];
  assign _015_[20] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[20];
  assign _015_[21] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[21];
  assign _015_[22] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[22];
  assign _015_[23] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[23];
  assign _015_[24] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[24];
  assign _015_[25] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[25];
  assign _015_[26] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[26];
  assign _015_[27] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[27];
  assign _015_[28] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[28];
  assign _015_[29] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[29];
  assign _015_[30] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[30];
  assign _015_[31] = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : lane_0[31];
  assign _016_[0] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[0] : _015_[0];
  assign _016_[1] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[1] : _015_[1];
  assign _016_[2] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[2] : _015_[2];
  assign _016_[3] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[3] : _015_[3];
  assign _016_[4] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[4] : _015_[4];
  assign _016_[5] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[5] : _015_[5];
  assign _016_[6] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[6] : _015_[6];
  assign _016_[7] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[7] : _015_[7];
  assign _016_[8] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[8] : _015_[8];
  assign _016_[9] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[9] : _015_[9];
  assign _016_[10] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[10] : _015_[10];
  assign _016_[11] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[11] : _015_[11];
  assign _016_[12] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[12] : _015_[12];
  assign _016_[13] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[13] : _015_[13];
  assign _016_[14] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[14] : _015_[14];
  assign _016_[15] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[15] : _015_[15];
  assign _016_[16] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[16] : _015_[16];
  assign _016_[17] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[17] : _015_[17];
  assign _016_[18] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[18] : _015_[18];
  assign _016_[19] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[19] : _015_[19];
  assign _016_[20] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[20] : _015_[20];
  assign _016_[21] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[21] : _015_[21];
  assign _016_[22] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[22] : _015_[22];
  assign _016_[23] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[23] : _015_[23];
  assign _016_[24] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[24] : _015_[24];
  assign _016_[25] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[25] : _015_[25];
  assign _016_[26] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[26] : _015_[26];
  assign _016_[27] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[27] : _015_[27];
  assign _016_[28] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[28] : _015_[28];
  assign _016_[29] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[29] : _015_[29];
  assign _016_[30] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[30] : _015_[30];
  assign _016_[31] = _008_ ? (* src = "striping_synth_synth.v:33" *) lane_0[31] : _015_[31];
  assign _000_[0] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[0];
  assign _000_[1] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[1];
  assign _000_[2] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[2];
  assign _000_[3] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[3];
  assign _000_[4] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[4];
  assign _000_[5] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[5];
  assign _000_[6] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[6];
  assign _000_[7] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[7];
  assign _000_[8] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[8];
  assign _000_[9] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[9];
  assign _000_[10] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[10];
  assign _000_[11] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[11];
  assign _000_[12] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[12];
  assign _000_[13] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[13];
  assign _000_[14] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[14];
  assign _000_[15] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[15];
  assign _000_[16] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[16];
  assign _000_[17] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[17];
  assign _000_[18] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[18];
  assign _000_[19] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[19];
  assign _000_[20] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[20];
  assign _000_[21] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[21];
  assign _000_[22] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[22];
  assign _000_[23] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[23];
  assign _000_[24] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[24];
  assign _000_[25] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[25];
  assign _000_[26] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[26];
  assign _000_[27] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[27];
  assign _000_[28] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[28];
  assign _000_[29] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[29];
  assign _000_[30] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[30];
  assign _000_[31] = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _017_[31];
  assign _020_ = _008_ ? (* src = "striping_synth_synth.v:33" *) _005_ : _019_;
  assign _018_ = _010_ ? (* src = "striping_synth_synth.v:44" *) _005_ : 1'h0;
  assign _019_ = _009_ ? (* src = "striping_synth_synth.v:39" *) _005_ : _018_;
  assign _021_ = _007_ ? (* src = "striping_synth_synth.v:26" *) _005_ : _020_;
  assign _002_ = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _021_;
  assign _024_ = _008_ ? (* src = "striping_synth_synth.v:33" *) 1'h1 : _023_;
  assign _022_ = _010_ ? (* src = "striping_synth_synth.v:44" *) 1'h0 : valid_1;
  assign _023_ = _009_ ? (* src = "striping_synth_synth.v:39" *) valid_1 : _022_;
  assign _025_ = _007_ ? (* src = "striping_synth_synth.v:26" *) valid_1 : _024_;
  assign _004_ = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _025_;
  assign _028_ = _007_ ? (* src = "striping_synth_synth.v:26" *) 1'h1 : _027_;
  assign _026_ = _009_ ? (* src = "striping_synth_synth.v:39" *) 1'h0 : valid_0;
  assign _027_ = _008_ ? (* src = "striping_synth_synth.v:33" *) valid_0 : _026_;
  assign _003_ = reset ? (* src = "striping_synth_synth.v:15" *) 1'h0 : _028_;
  assign _005_ = ~(* src = "striping_synth_synth.v:39" *) selector;
  assign _006_ = ~(* src = "striping_synth_synth.v:44" *) valid_in;
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      valid_0 <= _003_;
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      valid_1 <= _004_;
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      selector <= _002_;
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[0] <= _000_[0];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[1] <= _000_[1];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[2] <= _000_[2];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[3] <= _000_[3];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[4] <= _000_[4];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[5] <= _000_[5];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[6] <= _000_[6];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[7] <= _000_[7];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[8] <= _000_[8];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[9] <= _000_[9];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[10] <= _000_[10];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[11] <= _000_[11];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[12] <= _000_[12];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[13] <= _000_[13];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[14] <= _000_[14];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[15] <= _000_[15];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[16] <= _000_[16];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[17] <= _000_[17];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[18] <= _000_[18];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[19] <= _000_[19];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[20] <= _000_[20];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[21] <= _000_[21];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[22] <= _000_[22];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[23] <= _000_[23];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[24] <= _000_[24];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[25] <= _000_[25];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[26] <= _000_[26];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[27] <= _000_[27];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[28] <= _000_[28];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[29] <= _000_[29];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[30] <= _000_[30];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_0[31] <= _000_[31];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[0] <= _001_[0];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[1] <= _001_[1];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[2] <= _001_[2];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[3] <= _001_[3];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[4] <= _001_[4];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[5] <= _001_[5];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[6] <= _001_[6];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[7] <= _001_[7];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[8] <= _001_[8];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[9] <= _001_[9];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[10] <= _001_[10];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[11] <= _001_[11];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[12] <= _001_[12];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[13] <= _001_[13];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[14] <= _001_[14];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[15] <= _001_[15];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[16] <= _001_[16];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[17] <= _001_[17];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[18] <= _001_[18];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[19] <= _001_[19];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[20] <= _001_[20];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[21] <= _001_[21];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[22] <= _001_[22];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[23] <= _001_[23];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[24] <= _001_[24];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[25] <= _001_[25];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[26] <= _001_[26];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[27] <= _001_[27];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[28] <= _001_[28];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[29] <= _001_[29];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[30] <= _001_[30];
  (* src = "striping_synth_synth.v:13" *)
  always @(posedge clk_2f)
      lane_1[31] <= _001_[31];
endmodule
