/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "paralelo_serial_synth.v:1" *)
module paralelo_serial_synth(clk_4f, clk_32f, data_in, valid_in, reset, data2send, data_out);
  (* src = "paralelo_serial_synth.v:33" *)
  wire [7:0] _000_;
  (* src = "paralelo_serial_synth.v:33" *)
  wire _001_;
  (* src = "paralelo_serial_synth.v:33" *)
  wire [2:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  (* src = "paralelo_serial_synth.v:4" *)
  input clk_32f;
  (* src = "paralelo_serial_synth.v:3" *)
  input clk_4f;
  (* src = "paralelo_serial_synth.v:8" *)
  output [7:0] data2send;
  (* src = "paralelo_serial_synth.v:5" *)
  input [7:0] data_in;
  (* src = "paralelo_serial_synth.v:9" *)
  output data_out;
  (* src = "paralelo_serial_synth.v:7" *)
  input reset;
  (* src = "paralelo_serial_synth.v:11" *)
  wire [2:0] selector1;
  (* src = "paralelo_serial_synth.v:6" *)
  input valid_in;
  NOT _056_ (
    .A(selector1[2]),
    .Y(_003_)
  );
  NOT _057_ (
    .A(selector1[1]),
    .Y(_004_)
  );
  NOT _058_ (
    .A(valid_in),
    .Y(_005_)
  );
  NOT _059_ (
    .A(reset),
    .Y(_006_)
  );
  NOT _060_ (
    .A(data_in[0]),
    .Y(_007_)
  );
  NOT _061_ (
    .A(data_in[1]),
    .Y(_008_)
  );
  NOT _062_ (
    .A(data_in[2]),
    .Y(_009_)
  );
  NOT _063_ (
    .A(data_in[4]),
    .Y(_010_)
  );
  NOT _064_ (
    .A(data_in[6]),
    .Y(_011_)
  );
  NAND _065_ (
    .A(selector1[0]),
    .B(valid_in),
    .Y(_012_)
  );
  NOR _066_ (
    .A(selector1[0]),
    .B(valid_in),
    .Y(_013_)
  );
  NAND _067_ (
    .A(valid_in),
    .B(_006_),
    .Y(_014_)
  );
  NAND _068_ (
    .A(_006_),
    .B(_012_),
    .Y(_015_)
  );
  NOR _069_ (
    .A(_013_),
    .B(_015_),
    .Y(_002_[0])
  );
  NAND _070_ (
    .A(selector1[0]),
    .B(selector1[1]),
    .Y(_016_)
  );
  NOT _071_ (
    .A(_016_),
    .Y(_017_)
  );
  NOR _072_ (
    .A(_004_),
    .B(_012_),
    .Y(_018_)
  );
  NAND _073_ (
    .A(_004_),
    .B(_012_),
    .Y(_019_)
  );
  NAND _074_ (
    .A(_006_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _075_ (
    .A(_018_),
    .B(_020_),
    .Y(_002_[1])
  );
  NOR _076_ (
    .A(selector1[2]),
    .B(_018_),
    .Y(_021_)
  );
  NOR _077_ (
    .A(_003_),
    .B(_004_),
    .Y(_022_)
  );
  NAND _078_ (
    .A(selector1[2]),
    .B(_018_),
    .Y(_023_)
  );
  NAND _079_ (
    .A(_006_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _080_ (
    .A(_021_),
    .B(_024_),
    .Y(_002_[2])
  );
  NOR _081_ (
    .A(_007_),
    .B(_014_),
    .Y(_000_[0])
  );
  NOR _082_ (
    .A(_008_),
    .B(_014_),
    .Y(_000_[1])
  );
  NOR _083_ (
    .A(_005_),
    .B(data_in[2]),
    .Y(_025_)
  );
  NOR _084_ (
    .A(reset),
    .B(_025_),
    .Y(_000_[2])
  );
  NOR _085_ (
    .A(_005_),
    .B(data_in[3]),
    .Y(_026_)
  );
  NOR _086_ (
    .A(reset),
    .B(_026_),
    .Y(_000_[3])
  );
  NOR _087_ (
    .A(_005_),
    .B(data_in[4]),
    .Y(_027_)
  );
  NOR _088_ (
    .A(reset),
    .B(_027_),
    .Y(_000_[4])
  );
  NOR _089_ (
    .A(_005_),
    .B(data_in[5]),
    .Y(_028_)
  );
  NOR _090_ (
    .A(reset),
    .B(_028_),
    .Y(_000_[5])
  );
  NOR _091_ (
    .A(_011_),
    .B(_014_),
    .Y(_000_[6])
  );
  NOR _092_ (
    .A(_005_),
    .B(data_in[7]),
    .Y(_029_)
  );
  NOR _093_ (
    .A(reset),
    .B(_029_),
    .Y(_000_[7])
  );
  NOR _094_ (
    .A(selector1[0]),
    .B(selector1[1]),
    .Y(_030_)
  );
  NAND _095_ (
    .A(data_in[7]),
    .B(_030_),
    .Y(_031_)
  );
  NAND _096_ (
    .A(_003_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _097_ (
    .A(selector1[0]),
    .B(_004_),
    .Y(_033_)
  );
  NAND _098_ (
    .A(data_in[5]),
    .B(_033_),
    .Y(_034_)
  );
  NOR _099_ (
    .A(_010_),
    .B(_016_),
    .Y(_035_)
  );
  NAND _100_ (
    .A(selector1[0]),
    .B(_004_),
    .Y(_036_)
  );
  NOR _101_ (
    .A(_011_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _102_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _103_ (
    .A(_034_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _104_ (
    .A(_032_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _105_ (
    .A(data_in[3]),
    .B(_030_),
    .Y(_041_)
  );
  NOR _106_ (
    .A(_009_),
    .B(_036_),
    .Y(_042_)
  );
  NAND _107_ (
    .A(data_in[1]),
    .B(_033_),
    .Y(_043_)
  );
  NAND _108_ (
    .A(data_in[0]),
    .B(_017_),
    .Y(_044_)
  );
  NAND _109_ (
    .A(_041_),
    .B(_043_),
    .Y(_045_)
  );
  NOR _110_ (
    .A(_003_),
    .B(_042_),
    .Y(_046_)
  );
  NAND _111_ (
    .A(_044_),
    .B(_046_),
    .Y(_047_)
  );
  NOR _112_ (
    .A(_045_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _113_ (
    .A(_040_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _114_ (
    .A(_005_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _115_ (
    .A(selector1[2]),
    .B(_036_),
    .Y(_051_)
  );
  NOR _116_ (
    .A(_022_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _117_ (
    .A(valid_in),
    .B(_052_),
    .Y(_053_)
  );
  NOR _118_ (
    .A(reset),
    .B(_053_),
    .Y(_054_)
  );
  NOT _119_ (
    .A(_054_),
    .Y(_055_)
  );
  NOR _120_ (
    .A(_050_),
    .B(_055_),
    .Y(_001_)
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _121_ (
    .C(clk_32f),
    .D(_001_),
    .Q(data_out)
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _122_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(selector1[0])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _123_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(selector1[1])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _124_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(selector1[2])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _125_ (
    .C(clk_32f),
    .D(_000_[0]),
    .Q(data2send[0])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _126_ (
    .C(clk_32f),
    .D(_000_[1]),
    .Q(data2send[1])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _127_ (
    .C(clk_32f),
    .D(_000_[2]),
    .Q(data2send[2])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _128_ (
    .C(clk_32f),
    .D(_000_[3]),
    .Q(data2send[3])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _129_ (
    .C(clk_32f),
    .D(_000_[4]),
    .Q(data2send[4])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _130_ (
    .C(clk_32f),
    .D(_000_[5]),
    .Q(data2send[5])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _131_ (
    .C(clk_32f),
    .D(_000_[6]),
    .Q(data2send[6])
  );
  (* src = "paralelo_serial_synth.v:33" *)
  DFF _132_ (
    .C(clk_32f),
    .D(_000_[7]),
    .Q(data2send[7])
  );
endmodule
