/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "serial_paralelo_synth.v:1" *)
module serial_paralelo_synth(clk_4f, clk_32f, reset, data_in, active, valid_out, data_out);
  (* src = "serial_paralelo_synth.v:13" *)
  wire [31:0] BC_counter;
  (* src = "serial_paralelo_synth.v:7" *)
  output active;
  (* src = "serial_paralelo_synth.v:4" *)
  input clk_32f;
  (* src = "serial_paralelo_synth.v:3" *)
  input clk_4f;
  (* src = "serial_paralelo_synth.v:6" *)
  input data_in;
  (* src = "serial_paralelo_synth.v:10" *)
  output [7:0] data_out;
  (* src = "serial_paralelo_synth.v:5" *)
  input reset;
  (* src = "serial_paralelo_synth.v:8" *)
  output valid_out;
  assign BC_counter = 32'd0;
  assign active = 1'h0;
  assign data_out = 8'h00;
  assign valid_out = 1'h0;
endmodule
